- name: Ensure user variable is defined
  ansible.builtin.assert:
    that:
      - user is defined
      - user | length > 0
    fail_msg: "You must provide the variable 'user'. Play cannot continue."

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: yes
  become: true
