- import_tasks: user_version_var_verification.yml

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  become: true

- name: Uninstall conflicting Docker packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  loop:
    - docker.io
    - docker-doc
    - docker-compose
    - docker-compose-v2
    - podman-docker
    - containerd
    - runc
  become: true
  ignore_errors: yes 

- name: Set Ubuntu codename for Docker repo
  set_fact:
    docker_ubuntu_codename: >-
      {% if ansible_distribution == 'Linux Mint' %}
        {{ mint_to_ubuntu[ansible_lsb.codename] }}
      {% else %}
        {{ ansible_lsb.codename }}
      {% endif %}

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory
    mode: '0755'
  become: true

- name: Download Docker GPG key
  ansible.builtin.get_url: 
    url: https://download.docker.com/linux/ubuntu/gpg 
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Add Docker apt repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ arch_map[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ docker_ubuntu_codename | trim }} stable
    mode: '0644'
  become: true

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes
  become: true

- import_tasks: install_selected_version.yml
